<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bandung</name>
   <tag></tag>
   <elementGuidId>d59671db-60dd-41ce-b916-98a04228cfa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-suggestion-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bigsearch-query-location-suggestion-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a77d906c-01b5-4e83-96f6-c1c8c40c95a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5fb0482b-3159-4fdb-a5ad-29aad7b8c309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>93f03c30-f395-4d5c-b469-3f0942660184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-suggestion-0</value>
      <webElementGuid>d7e19935-fac9-4ea3-becb-a19e6194a66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b40d1e92-5674-4e46-8890-bfd4cb47ca7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>7a73ea7a-e5ec-4894-9186-63b533fab145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prefix</name>
      <type>Main</type>
      <value>SYSTEM_LOCATION_STROKED</value>
      <webElementGuid>10efe21c-7d9b-48c0-90c0-ce0c11de9413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c569q9j atm_r2_1j28jx2 atm_5j_kitwna atm_9j_tlke0l atm_9s_1txwivl atm_cx_exct8b atm_gw_1rrn7iu atm_l8_ftgil2 atm_kd_glywfm_1w3cfyq atm_uc_aaiy6o_1w3cfyq atm_26_1qwqy05_1w3cfyq atm_70_6ezzhz_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_uc_aaiy6o_pfnrn2_1oszvuo atm_26_1qwqy05_pfnrn2_1oszvuo atm_70_6ezzhz_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_26_jk66pa_1nos8r_uv4tnr atm_26_jk66pa_csw3t1 c16b4zta atm_26_jk66pa dir dir-ltr</value>
      <webElementGuid>c1da0c7b-bfb9-477d-ab76-82fe286eac80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bandung</value>
      <webElementGuid>049baa5c-e7ce-4a9a-897b-6a54422e5100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-application&quot;)/div[1]/div[@class=&quot;t1bgcr6e  cjz5kiq&quot;]/div[1]/div[1]/div[@class=&quot;r9m3m4o atm_eohtre_1wfwpv5 atm_1gwwzir_u29brm atm_eohtre_mm87nz__jx8car atm_1gwwzir_rw9lz9__jx8car dir dir-ltr&quot;]/div[@class=&quot;m1wgxt7p atm_lcucu6_exct8b atm_ys9she_69rp3d__jx8car atm_ys9she_12mkxmp__1z0u2lb atm_lcucu6_1tcgj5g__kgj4qw atm_lcucu6_1tcgj5g__oggzyc atm_lcucu6_1vi7ecw__1v156lz atm_lcucu6_1vi7ecw__qky54b atm_lcucu6_fyhuej__jx8car dir dir-ltr&quot;]/div[@class=&quot;w1hvh9qj atm_mk_1if85x1 atm_tk_idpfg4 atm_vy_1osqo2v atm_wq_zo7u8 atm_h3_1wmurcz whb0xmj atm_e2_n7od8j atm_26_n7od8j atm_3f_n7od8j atm_e2_n7od8j__qky54b dir dir-ltr&quot;]/div[@class=&quot;c1yo0219 atm_9s_1txwivl_vmtskl atm_92_1yyfdc7_vmtskl atm_9s_1txwivl_9in345 atm_92_1yyfdc7_9in345 dir dir-ltr&quot;]/div[1]/header[@class=&quot;c1ftp51f atm_9s_1txwivl atm_fc_1yb4nlp atm_h_1h6ojuz atm_gi_xjk4d9 atm_j3_kecc4u atm_lk_1ph3nq8 atm_ll_1ph3nq8 atm_e2_u29brm atm_j3_1vvhni0__6ldadd atm_lk_n9wab5__1v156lz atm_ll_n9wab5__1v156lz atm_lk_dnsvzo__jx8car atm_ll_dnsvzo__jx8car atm_e2_rw9lz9__jx8car dir dir-ltr&quot;]/form[@class=&quot;f1hztvqy atm_vy_1osqo2v atm_e2_1osqo2v atm_mk_stnw88 atm_tk_idpfg4 atm_fq_idpfg4 atm_lh_ke7zzc atm_wq_idpfg4 dir dir-ltr&quot;]/div[@class=&quot;csjaj27 atm_vy_1osqo2v atm_9s_1txwivl atm_h_1h6ojuz atm_ar_1bp4okc atm_mk_h2mmj6 atm_wq_kb7nvz atm_h3_ftgil2__jx8car dir dir-ltr&quot;]/div[1]/div[@class=&quot;cwxaa06 atm_mk_stnw88 atm_fq_1ssbidh atm_tr_zr6sja atm_j3_1v7idld atm_vy_1osqo2v atm_e2_1k4yqc2 atm_9s_1txwivl atm_5j_1vi7ecw atm_cx_1fwxnve atm_fc_1yb4nlp atm_h_1h6ojuz dir dir-ltr&quot;]/div[@class=&quot;p1gy195r atm_mk_stnw88 atm_vy_1osqo2v atm_e2_1wugsn5 atm_tk_1osqo2v atm_mj_glywfm atm_h3_1fwxnve dir dir-ltr&quot;]/div[@class=&quot;p1nt1a2q atm_mk_stnw88 atm_mj_1rj4a2z atm_aj_19ksii2 atm_8w_1rrkn1e dir dir-ltr&quot;]/div[@class=&quot;pkny13m atm_tw_n17gr9 atm_vy_1osqo2v atm_e2_1osqo2v atm_26_1p8m8iw atm_7i_1qlzsek dir dir-ltr&quot;]/div[@class=&quot;piqlc25 atm_vy_1osqo2v atm_e2_1osqo2v atm_9s_1txwivl atm_fc_1h6ojuz p1tlhulc atm_l8_1cycdsj pgigb2o atm_iy_1p2dahq atm_l1_15zigw atm_l2_1f51e7f atm_p5_p27btl atm_9s_1ulexfb_14pyf7n atm_vy_1skhajo_14pyf7n atm_26_1j28jx2_15m0xli atm_2a_1ntvvq4_1v32vyo atm_2d_1qrrl4z_1v32vyo atm_5j_1skhajo_1v32vyo atm_3f_1p8s0ws_1v32vyo atm_h3_1pa919l_1s8n6b atm_gq_1pa919l_he8sou dir dir-ltr&quot;]/div[@id=&quot;bigsearch-query-location-listbox&quot;]/div[@id=&quot;bigsearch-query-location-suggestion-0&quot;]</value>
      <webElementGuid>1c05256d-aff8-49fd-89e9-6e3d4f8687ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-suggestion-0']</value>
      <webElementGuid>797cf3b3-d25c-47d1-85bd-5516f589454e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-listbox']/div</value>
      <webElementGuid>73372f06-1292-4c2e-8064-76f9b37ac2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[6]</value>
      <webElementGuid>93be6ca5-f958-48ac-9d41-287deea5fb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add guests'])[1]/following::div[10]</value>
      <webElementGuid>8d894e75-02f8-44ce-a851-74a24454e4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lembang'])[1]/preceding::div[5]</value>
      <webElementGuid>265f3b04-6069-44de-8d84-1835b890f651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div</value>
      <webElementGuid>009830ee-8fe2-4784-bda1-2a3d264eb91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'bigsearch-query-location-suggestion-0' and (text() = 'Bandung' or . = 'Bandung')]</value>
      <webElementGuid>a0e8f513-398c-4e95-b0d4-44530f3ea55f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
